import mongoose, { Schema, type Document } from 'mongoose';

interface HiddenResult {
  id: string;
  passed: boolean;
}

interface ISubmission {
  _id?: string;
  userId: string;
  problemId: string;
  language: string;
  code: string;
  status: 'accepted' | 'wrong_answer' | 'runtime_error' | 'compile_error';
  passedTests?: number;
  totalTests?: number;
  runtimeMs?: number;
  /**
   * UUID v4 generated by the client for each execute() call. Two
   * submissions from the same session share a sessionId. Purely
   * audit-only today; will be used to correlate client reports with
   * server re-runs once server-side judging ships.
   */
  sessionId?: string;
  /**
   * Per-hidden-test boolean vector. Does NOT contain outputs or inputs.
   * The ID format is `${problemId}:${testIndex}` on the client side, and
   * is validated against the server's actual hidden test list at
   * submission time.
   */
  hiddenResults?: HiddenResult[];
}

export interface SubmissionDocument extends Omit<ISubmission, '_id'>, Document {}

const hiddenResultSchema = new Schema<HiddenResult>(
  {
    id: { type: String, required: true },
    passed: { type: Boolean, required: true },
  },
  { _id: false }
);

const submissionSchema = new Schema<SubmissionDocument>(
  {
    userId: { type: String, required: true, index: true },
    problemId: { type: String, required: true, index: true },
    language: { type: String, required: true },
    code: { type: String, required: true },
    status: {
      type: String,
      enum: ['accepted', 'wrong_answer', 'runtime_error', 'compile_error'],
      required: true,
    },
    passedTests: { type: Number, default: 0 },
    totalTests: { type: Number, default: 0 },
    runtimeMs: { type: Number },
    sessionId: { type: String, index: true },
    hiddenResults: { type: [hiddenResultSchema], default: undefined },
  },
  { timestamps: true }
);

submissionSchema.index({ userId: 1, problemId: 1, createdAt: -1 });

export const Submission = mongoose.model<SubmissionDocument>(
  'Submission',
  submissionSchema
);